version: '3.8'
services:
  eureka-server:
    image: eurekaserver
    build:
      context: ../eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - eureka-net

  q4:
    image: q4
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
    networks:
      - eureka-net

networks:
  eureka-net:
