apiVersion: apps/v1
kind: Deployment
metadata:
  name: q2
spec:
  selector:
    matchLabels:
      app: q2
  replicas: 3
  template:
    metadata:
      labels:
        app: q2
    spec:
      containers:
        - name: q2
          image: q2:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
            - name: EUREKA_SERVER_URI
              value: "http://eurekaserver:8761/eureka/"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:h2:mem:veiculo"
            - name: SPRING_DATASOURCE_USERNAME
              value: "sa"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "123456"
---
apiVersion: v1
kind: Service
metadata:
  name: q2
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 31002  # Escolha uma porta entre 30000 e 32767
  selector:
    app: q2