name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn -f q6/pom.xml clean package

      - name: Run tests
        run: mvn -f q6/pom.xml test

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: maven-build
          path: q6/target/*.jar
